# This name is used to identify the workflow
name: matrix strategy

# This name is displayed in the Actions tab of the repository
run-name: Matrix Strategy Workflow Run By ${{ github.actor }}

on:
  workflow_dispatch: {}

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22]
        node-version: [18.x, 20.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
      - run: npm run build

      - run: echo "OS= ${{ matrix.os }} Node= ${{ matrix.node-version }}"
