name: Deployment to Production on Beta Branch

on:
  push:
    branches:
      - beta

jobs:
  json:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJson(github) }}"

  deploy:
    if: startsWith(github.ref_name, 'release/')
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo "Deploying to Production environment"
