name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true
        default: "1.0.0"

  pull_request:
    types: [opened, synchronize]

jobs:
  create-new-release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Create new release
        run: |
          echo "Creating release ${{ github.event.inputs.version }}"
          git tag -a ${{ github.event.inputs.version }} -m "version ${{ github.event.inputs.version }}"
          git push origin ${{ github.event.inputs.version }}

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git fetch --tags
      - run: |
          tag=$(git tag --points-at)
          [[ tag =~ ^release ]] && publish=true || publish=false
          echo "$publish" >> $GITHUB_OUTPUT

  deploy:
    needs: check
    runs-on: ubuntu-latest
    if: ${{ needs.check.outputs.publish == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - run: echo "Deploying"
